# Generated by Django 3.2 on 2023-07-14 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0005_board_applied_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='applied_users',
        ),
    ]
