# Generated by Django 3.2 on 2023-07-14 09:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boardapp', '0007_apply'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='apply',
            unique_together={('board', 'user')},
        ),
    ]
