# Generated by Django 3.2 on 2023-07-14 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0008_alter_apply_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='apply',
            unique_together=set(),
        ),
    ]
